# Generated by Django 5.2 on 2025-05-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='stars',
            field=models.IntegerField(choices=[(1, '* '), (2, '* * '), (3, '* * * '), (4, '* * * * '), (5, '* * * * * '), (6, '* * * * * * '), (7, '* * * * * * * '), (8, '* * * * * * * * '), (9, '* * * * * * * * * '), (10, '* * * * * * * * * * ')], default=5),
        ),
    ]
